/* 
find coefficients for the function 
y = f(x) = a0 + a1*x + a2*x^2 + a3*x^3 + a4x^4
such that 
f(0) = y0, f(1) = y1, f(2) = y2, f'(0) = s0, f'(2) = s2
*/


e1: y0 = a0 + a1*0 + a2*0^2 + a3*0^3 + a4*0^4;
e2: y1 = a0 + a1*1 + a2*1^2 + a3*1^3 + a4*1^4;
e3: y2 = a0 + a1*2 + a2*2^2 + a3*2^3 + a4*2^4;
e4: s0 = a1 + 2*a2*0 + 3*a3*0^2 + 4*a4*0^3;
e5: s2 = a1 + 2*a2*2 + 3*a3*2^2 + 4*a4*2^3;
solve([e1, e2, e3, e4, e5], [a0, a1, a2, a3, a4]);
optimize(%);