/* 
find the solution vector [x1 x2 x3] to the matrix-equation:
|P2-P1 P2*Q2 -Q2| * |A0s| = |Q2^2*(P5-P2)|
|P3-P1 P3*Q3 -Q3|   |a|     |Q3^2*(P5-P3)|
|P4-P1 P4*Q4 -Q4|   |b|     |Q4^2*(P5-P4)|

A0s: A0^2, a: alpha, b: beta
*/

e1: (P2-P1)*A0s + P2*Q2*a - Q2*b = Q2^2*(P5-P2);
e2: (P3-P1)*A0s + P3*Q3*a - Q3*b = Q3^2*(P5-P3);
e3: (P4-P1)*A0s + P4*Q4*a - Q4*b = Q4^2*(P5-P4);
solve([e1, e2, e3], [A0s, a, b]);
optimize(%);

