/* 
find coefficients for the function y = f(x) = a0 + a1*x + a2*x^2 + a3*x^3
such that f(0) = y0, f(1) = y1, f(2) = y2, f'(1) = s1
where s1 is estimated as s1 = (y2-y0)/2
*/

e1: y0 = a0 + a1*0 + a2*0^2 + a3*0^3;
e2: y1 = a0 + a1*1 + a2*1^2 + a3*1^3;
e3: y2 = a0 + a1*2 + a2*2^2 + a3*2^3;
e4: s1 =      a1   + 2*a2*1 + 3*a3*1^2;
s1: (y2-y0)/2;
solve([e1, e2, e3, e4], [a0, a1, a2, a3]);
optimize(%);