/* 
find the solution vector [x1 x2 x3] to the matrix-equation:
|a11 a12 a13 a14| * |x1| = |b1|
|a21 a22 a23 a24|   |x2|   |b2|
|a31 a32 a33 a34|   |x3|   |b3|
|a41 a42 a43 a44|   |x4|   |b4|
*/

e1: a11*x1 + a12*x2 + a13*x3 + a14*x4 = b1;
e2: a21*x1 + a22*x2 + a23*x3 + a24*x4 = b2;
e3: a31*x1 + a32*x2 + a33*x3 + a34*x4 = b3;
e4: a41*x1 + a42*x2 + a43*x3 + a44*x4 = b4;
solve([e1, e2, e3, e4], [x1, x2, x3, x4]);
optimize(%);

